Sub:
  - [3,3,9]
  - [9,6,15]
  - [8,6,2]
  - [9,9,18]
  - [20,4,5]
Add:
  - [3,3,9]
  - [9,6,15]
  - [8,6,2]
  - [9,9,18]
  - [20,4,5]
Div:
  - [3,3,9]
  - [9,6,15]
  - [8,6,2]
  - [9,9,18]
  - [20,4,5]
Mul:
  - [3,3,9]
  - [9,6,15]
  - [8,6,2]
  - [9,9,18]
  - [20,4,5]
Mix:
  Add:
    A: (5,
    B: 6
  Sub:
    A: 8
    B: 4
  Expected: 15